server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/enesincekaraa/deskflow-config-repo
          default-label: main
          clone-on-start: true
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_TOKEN}

management:
  endpoints:
    web:
      exposure:
        include: "*"


